[package]
name = "github_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.18", features = ["blocking"] }
serde_json = "1.0.140"
clap = { version = "4.5.39", features = ["derive"] }
